version: 2

project_name: s5cmd

builds:
  - id: s5cmd
    binary: s5cmd
    ldflags:
      - -s -w
      - -X github.com/peak/s5cmd/v2/version.Version={{ .Tag }}
      - -X github.com/peak/s5cmd/v2/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: linux-amd64
    formats:
      - tar.gz
    name_template: "s5cmd_{{ .Version }}_Linux-64bit"

checksum:
  name_template: s5cmd_checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  draft: false
